[package]
name = "mousevpn-windows-client"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
fs2 = "0.4"
getrandom = "0.3"
mousevpn-client-wire = { path = "../client-wire" }
mousevpn-config = { path = "../config" }
mousevpn-crypto = { path = "../crypto" }
mousevpn-data-plane = { path = "../data-plane" }
mousevpn-protocol = { path = "../protocol" }
mousevpn-transport = { path = "../transport" }
serde = { version = "1.0", features = ["derive"] }
toml = "1.0"
zeroize = "1.8"

[target.'cfg(windows)'.dependencies]
wintun = "0.5.1"
windows-sys = { version = "0.61", features = [
    "Win32_Foundation",
    "Win32_NetworkManagement_IpHelper",
    "Win32_NetworkManagement_Ndis",
    "Win32_Networking_WinSock",
    "Win32_Security",
    "Win32_Security_Cryptography",
    "Win32_Security_Authorization",
    "Win32_Security_Isolation",
    "Win32_System_LibraryLoader",
    "Win32_System_Power",
    "Win32_System_Rpc",
    "Win32_NetworkManagement_WindowsFilteringPlatform",
    "Win32_System_Threading",
    "Win32_UI_WindowsAndMessaging",
] }

[lints.clippy]
all = "warn"
pedantic = "warn"
